FROM mcr.microsoft.com/dotnet/sdk:8.0 
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

RUN dotnet tool install --global dotnet-ef
ENV PATH="${PATH}:/root/.dotnet/tools"

COPY TodoApp .
RUN dotnet restore TodoApp.csproj

CMD ["dotnet", "run", "--urls", "http://0.0.0.0:8080"]

